name: CD Taller 2
on:
  workflow_dispatch:
    inputs:
      backend_url:
        description: URL del Backend que usará el navegador
        required: true
        default: http://localhost:8080
permissions:
  contents: read
jobs:
  deploy:
    runs-on:
      - self-hosted
      - linux
    steps:
      - uses: actions/checkout@v4
      - run: BACKEND_URL="${{ inputs.backend_url }}" docker compose up -d --build
